[database]
schema=FOCUS_TEST_GO_V1

[tables]
FOCUS=TEMP_OCI_FOCUS
TAG_KEYS=TEMP_OCI_FOCUS_TAG_KEYS
TAG_KEYS_REF=TEMP_OCI_FOCUS_TAG_KEYS
LOAD_STATUS=TEMP_OCI_FOCUS_LOAD_STATUS
FOCUS_STATS=TEMP_OCI_FOCUS_STATS
RESOURCES=TEMP_OCI_RESOURCES
RATE_CARD=TEMP_OCI_FOCUS_RATE_CARD