#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ -f "$script_dir/.env" ]] && { set -a; source "$script_dir/.env"; set +a; }

ADMIN_USER=${DB_ADMIN_USER:-ADMIN}
ADMIN_PASS=${DB_ADMIN_PASSWORD:-}
DB_CONN=${DB_TNS_ALIAS:-}
TARGET_SCHEMA=${TARGET_SCHEMA:-}
TARGET_PASS=${TARGET_SCHEMA_PASSWORD:-}
CONFIG_FILE=${FOCUS_CONFIG_FILE:-$script_dir/focus.conf}

if [ -z "$ADMIN_USER" ] || [ -z "$ADMIN_PASS" ] || [ -z "$DB_CONN" ] || [ -z "$TARGET_SCHEMA" ] || [ -z "$TARGET_PASS" ]; then
  echo "Usage:"
  echo "Set DB_ADMIN_PASSWORD, DB_TNS_ALIAS, TARGET_SCHEMA, and TARGET_SCHEMA_PASSWORD."
  exit 1
fi

[[ "$TARGET_SCHEMA" =~ ^[A-Za-z][A-Za-z0-9_\$#]*$ ]] || {
  echo "Invalid TARGET_SCHEMA: $TARGET_SCHEMA" >&2
  exit 1
}

if [ ! -f "$CONFIG_FILE" ]; then
  echo "Config file not found: $CONFIG_FILE"
  exit 1
fi

SCHEMA=$TARGET_SCHEMA
ADMIN_PASS_SQL=${ADMIN_PASS//\"/\"\"}

T_FOCUS=TEMP_OCI_FOCUS
T_TAGS=TEMP_OCI_FOCUS_TAGS
T_TAG_KEYS=TEMP_OCI_FOCUS_TAG_KEYS
T_STATS=TEMP_OCI_FOCUS_STATS
T_LOAD=TEMP_OCI_FOCUS_LOAD_STATUS
T_REF=TEMP_OCI_FOCUS_REFERENCE

FQN_FOCUS=${SCHEMA}.${T_FOCUS}
FQN_TAGS=${SCHEMA}.${T_TAGS}
FQN_TAG_KEYS=${SCHEMA}.${T_TAG_KEYS}
FQN_STATS=${SCHEMA}.${T_STATS}
FQN_LOAD=${SCHEMA}.${T_LOAD}
FQN_REF=${SCHEMA}.${T_REF}

sqlplus -L /nolog <<EOF

SET DEFINE OFF
CONNECT ${ADMIN_USER}/"${ADMIN_PASS_SQL}"@"${DB_CONN}"

SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO OFF

PROMPT ============================================
PROMPT STARTING SCHEMA DEPLOYMENT
PROMPT ============================================

PROMPT ---- Creating user if not exists ----

DROP USER ${SCHEMA} CASCADE;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count 
  FROM all_users 
  WHERE username = UPPER('${SCHEMA}');

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER ${SCHEMA} IDENTIFIED BY "${TARGET_PASS}"';
    DBMS_OUTPUT.PUT_LINE('User created');
  ELSE
    DBMS_OUTPUT.PUT_LINE('User already exists');
  END IF;
END;
/
PROMPT ---- Granting privileges ----

GRANT CONNECT, DWROLE TO ${SCHEMA};
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE TO ${SCHEMA};
GRANT UNLIMITED TABLESPACE TO ${SCHEMA};



PROMPT ---- Switching to schema ${SCHEMA} ----
ALTER SESSION SET CURRENT_SCHEMA=${SCHEMA};



PROMPT ---- Creating main table ----


-- =====================================
-- Create main table
-- =====================================
CREATE TABLE ${FQN_FOCUS}
(
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
	"SOURCE_TENANT_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SOURCE_FILE_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"BILLING_ACCOUNT_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"BILLING_ACCOUNT_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"BILLING_ACCOUNT_TYPE" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SUB_ACCOUNT_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SUB_ACCOUNT_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SUB_ACCOUNT_TYPE" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"INVOICE_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"INVOICE_ISSUER" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"PROVIDER" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"PUBLISHER" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"PRICING_CATEGORY" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"PRICING_CURRENCY_CONTRACTED_UP" NUMBER,
	"PRICING_CURRENCY_EFFECTIVE_COST" NUMBER,
	"PRICING_CURRENCY_LIST_UNIT_PRICE" NUMBER,
	"PRICING_QUANTITY" NUMBER,
	"PRICING_UNIT" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"BILLING_PERIOD_START" DATE,
	"BILLING_PERIOD_END" DATE,
	"CHARGE_PERIOD_START" DATE,
	"CHARGE_PERIOD_END" DATE,
	"BILLED_COST" NUMBER,
	"BILLING_CURRENCY" VARCHAR2(100) COLLATE "USING_NLS_COMP",
	"CONSUMED_QUANTITY" NUMBER,
	"CONSUMED_UNIT" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"CONTRACTED_COST" NUMBER,
	"CONTRACTED_UNIT_PRICE" NUMBER,
	"EFFECTIVE_COST" NUMBER,
	"LIST_COST" NUMBER,
	"LIST_UNIT_PRICE" NUMBER,
	"AVAILABILITY_ZONE" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"REGION_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"REGION_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"RESOURCE_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"RESOURCE_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"RESOURCE_TYPE" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"TAGS" VARCHAR2(32627) COLLATE "USING_NLS_COMP",
	"SERVICE_CATEGORY" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SERVICE_SUB_CATEGORY" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SERVICE_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"CAPACITY_RESERVATION_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"CAPACITY_RESERVATION_STATUS" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"CHARGE_CATEGORY" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"CHARGE_CLASS" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"CHARGE_DESCRIPTION" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"CHARGE_FREQUENCY" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"COMMITMENT_DISCOUNT_CATEGORY" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"COMMITMENT_DISCOUNT_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"COMMITMENT_DISCOUNT_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"COMMITMENT_DISCOUNT_QUANTITY" NUMBER,
	"COMMITMENT_DISCOUNT_STATUS" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"COMMITMENT_DISCOUNT_TYPE" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"COMMITMENT_DISCOUNT_UNIT" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SKU_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SKU_PRICE_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SKU_PRICE_DETAILS" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SKU_METER" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"USAGE_QUANTITY" NUMBER,
	"USAGE_UNIT" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"OCI_REFERENCE_NUMBER" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"OCI_COMPARTMENT_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"OCI_COMPARTMENT_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"OCI_COMPARTMENT_PATH" VARCHAR2(4000) COLLATE "USING_NLS_COMP",
	"OCI_OVERAGE_FLAG" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"OCI_UNIT_PRICE_OVERAGE" NUMBER,
	"OCI_BILLED_QUANTITY_OVERAGE" NUMBER,
	"OCI_COST_OVERAGE" NUMBER,
	"OCI_ATTRIBUTED_USAGE" NUMBER,
	"OCI_ATTRIBUTED_COST" NUMBER,
	"OCI_BACK_REFERENCE_NUMBER" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"TAG_SPECIAL1" VARCHAR2(4000) COLLATE "USING_NLS_COMP",
	"TAG_SPECIAL2" VARCHAR2(4000) COLLATE "USING_NLS_COMP",
	"TAG_SPECIAL3" VARCHAR2(4000) COLLATE "USING_NLS_COMP",
	"TAG_SPECIAL4" VARCHAR2(4000) COLLATE "USING_NLS_COMP",
    "LOAD_DATE"            DATE DEFAULT SYSDATE
--    CONSTRAINT TEMP_OCI_FOCUS_PK PRIMARY KEY (ID)
)
COMPRESS FOR QUERY HIGH
PARTITION BY RANGE (CHARGE_PERIOD_START)
INTERVAL (NUMTOYMINTERVAL(1,'MONTH'))
(
    PARTITION p_init VALUES LESS THAN (DATE '2025-01-01')
);




-- CREATE INDEX ${SCHEMA}.TEMP_OCI_FOCUS_TENANT_DT
-- ON ${FQN_FOCUS} (SOURCE_TENANT_NAME, CHARGE_PERIOD_START)
-- LOCAL;

-- CREATE INDEX ${SCHEMA}.TEMP_OCI_FOCUS_RESOURCE
-- ON ${FQN_FOCUS} (RESOURCE_ID)
-- LOCAL;

 


-- =====================================
-- Create TEMP_OCI_FOCUS_LOAD_STATUS
-- =====================================
CREATE TABLE ${FQN_LOAD}
(
  SOURCE_TENANT_NAME VARCHAR2(1000) NOT NULL,
  FILE_TYPE          VARCHAR2(1000) NOT NULL,
  FILE_ID            VARCHAR2(1000) NOT NULL,
  FILE_NAME          VARCHAR2(1000) NOT NULL,
  FILE_DATE          DATE,
  FILE_SIZE          NUMBER,
  NUM_ROWS           NUMBER,
  LOAD_START_TIME    DATE,
  LOAD_END_TIME      DATE,
  AGENT_VERSION      VARCHAR2(100),
  BATCH_ID           NUMBER,
  BATCH_TOTAL        NUMBER,
  CONSTRAINT TEMP_OCI_FOCUS_LOAD_STATUS_PK
  PRIMARY KEY (SOURCE_TENANT_NAME, FILE_NAME)
);

-- Create TEMP_OCI_FOCUS_STATS
-- =====================================
CREATE TABLE ${FQN_STATS}
(
  SOURCE_TENANT_NAME   VARCHAR2(1000),
  SOURCE_FILE_ID       VARCHAR2(1000),
  CHARGE_PERIOD_START  DATE,
  NUM_ROWS             NUMBER,
  EFFECTIVE_COST       NUMBER,
  BILLING_CURRENCY     VARCHAR2(1000),
  UPDATE_DATE          DATE,
  AGENT_VERSION        VARCHAR2(30),
  CONSTRAINT TEMP_OCI_FOCUS_STATS_PK
  PRIMARY KEY (SOURCE_TENANT_NAME, SOURCE_FILE_ID, CHARGE_PERIOD_START)
);



CREATE TABLE ${FQN_TAG_KEYS}
(
    "SOURCE_TENANT_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
    "TAG_KEY"            VARCHAR2(1000) COLLATE "USING_NLS_COMP",
    "TAG_VALUE"          VARCHAR2(4000) COLLATE "USING_NLS_COMP",
    CONSTRAINT TEMP_OCI_FOCUS_TAG_KEYS_PK
        PRIMARY KEY ("SOURCE_TENANT_NAME", "TAG_KEY", "TAG_VALUE")
        USING INDEX ENABLE
);


CREATE TABLE ${FQN_REF}
(
    "SOURCE_TENANT_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
    "REF_TYPE"           VARCHAR2(1000) COLLATE "USING_NLS_COMP",
    "REF_NAME"           VARCHAR2(1000) COLLATE "USING_NLS_COMP",
    CONSTRAINT TEMP_OCI_FOCUS_REFERENCE_PK
    PRIMARY KEY ("SOURCE_TENANT_NAME", "REF_TYPE", "REF_NAME")
    USING INDEX ENABLE
)
DEFAULT COLLATION "USING_NLS_COMP";



-- drop  table ${FQN_TAGS} cascade constraints;
-- =====================================
-- Create TAGS table
-- =====================================
CREATE TABLE ${FQN_TAGS} (
    SOURCE_TENANT_NAME   VARCHAR2(200)   NOT NULL,
    RESOURCE_ID          VARCHAR2(500),
    CHARGE_PERIOD_START  VARCHAR2(200)           NOT NULL,
    TAG_KEY              VARCHAR2(200)   NOT NULL,
    TAG_VALUE            VARCHAR2(4000)
)
COMPRESS FOR QUERY HIGH
NOLOGGING;

CREATE INDEX TEMP_OCI_FOCUS_TAGS_IX1
ON ${FQN_TAGS} (TAG_KEY, TAG_VALUE)
NOLOGGING;

EXIT
EOF

echo "Schema objects created under ${SCHEMA}."
