-- Install optional OML4SQL analytics for TEMP_OCI_FOCUS in the current schema.
-- Run as the application schema owner. Required direct privilege:
--   GRANT CREATE MINING MODEL TO <schema>;
-- The script is idempotent for its FOCUS_OML_* tables, views, and package.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT Checking TEMP_OCI_FOCUS and OML privileges...
DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_count
  FROM USER_TABLES
  WHERE TABLE_NAME = 'TEMP_OCI_FOCUS';

  IF l_count = 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'TEMP_OCI_FOCUS does not exist in the current schema');
  END IF;

  SELECT COUNT(*) INTO l_count
  FROM USER_SYS_PRIVS
  WHERE PRIVILEGE = 'CREATE MINING MODEL';

  IF l_count = 0 THEN
    RAISE_APPLICATION_ERROR(
      -20002,
      'CREATE MINING MODEL must be granted directly to the current schema'
    );
  END IF;
END;
/

PROMPT Creating idempotent OML result tables...
DECLARE
  PROCEDURE create_if_missing(p_sql IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -955 THEN
        RAISE;
      END IF;
  END;
BEGIN
  create_if_missing(q'[
    CREATE TABLE FOCUS_OML_RUNS (
      RUN_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      RUN_AT_UTC TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
      STATUS VARCHAR2(30) NOT NULL,
      MESSAGE VARCHAR2(4000),
      OUTLIER_RATE NUMBER NOT NULL
    )]');

  create_if_missing(q'[
    CREATE TABLE FOCUS_OML_ANOMALIES (
      DIMENSION_TYPE VARCHAR2(20) NOT NULL,
      DIMENSION_VALUE VARCHAR2(4000) NOT NULL,
      COST_MONTH DATE NOT NULL,
      BILLING_CURRENCY VARCHAR2(100) NOT NULL,
      EFFECTIVE_COST NUMBER NOT NULL,
      ANOMALY_PROBABILITY NUMBER NOT NULL,
      PREDICTION NUMBER NOT NULL,
      MODEL_NAME VARCHAR2(128) NOT NULL
    )]');

  create_if_missing(q'[
    CREATE TABLE FOCUS_OML_FORECAST (
      CREATED_BY VARCHAR2(4000) NOT NULL,
      BILLING_CURRENCY VARCHAR2(100) NOT NULL,
      FORECAST_MONTH DATE NOT NULL,
      HORIZON_MONTHS NUMBER NOT NULL,
      PREDICTION NUMBER NOT NULL,
      LOWER_BOUND NUMBER NOT NULL,
      UPPER_BOUND NUMBER NOT NULL
    )]');

  create_if_missing(q'[
    CREATE TABLE FOCUS_OML_TOP_USER (
      CREATED_BY VARCHAR2(4000) NOT NULL,
      BILLING_CURRENCY VARCHAR2(100) NOT NULL,
      YTD_COST NUMBER NOT NULL
    )]');

  create_if_missing(q'[
    CREATE TABLE FOCUS_OML_TOP_USER_TS (
      TIME_INDEX NUMBER PRIMARY KEY,
      COST_MONTH DATE NOT NULL,
      EFFECTIVE_COST NUMBER NOT NULL
    )]');
END;
/

PROMPT Creating monthly cost and feature views...
CREATE OR REPLACE VIEW FOCUS_OML_DIM_MONTHLY AS
SELECT
  DIMENSION_TYPE,
  DIMENSION_VALUE,
  COST_MONTH,
  BILLING_CURRENCY,
  SUM(EFFECTIVE_COST) AS EFFECTIVE_COST,
  SUM(ROW_COUNT) AS ROW_COUNT
FROM (
  SELECT
    'TOTAL' AS DIMENSION_TYPE,
    '(all costs)' AS DIMENSION_VALUE,
    TRUNC(CHARGE_PERIOD_START, 'MM') AS COST_MONTH,
    NVL(TRIM(BILLING_CURRENCY), '(not provided)') AS BILLING_CURRENCY,
    NVL(EFFECTIVE_COST, 0) AS EFFECTIVE_COST,
    1 AS ROW_COUNT
  FROM TEMP_OCI_FOCUS
  WHERE CHARGE_PERIOD_START IS NOT NULL

  UNION ALL

  SELECT
    'SERVICE',
    NVL(TRIM(SERVICE_NAME), '(unassigned)'),
    TRUNC(CHARGE_PERIOD_START, 'MM'),
    NVL(TRIM(BILLING_CURRENCY), '(not provided)'),
    NVL(EFFECTIVE_COST, 0),
    1
  FROM TEMP_OCI_FOCUS
  WHERE CHARGE_PERIOD_START IS NOT NULL

  UNION ALL

  SELECT
    'REGION',
    NVL(TRIM(REGION_NAME), NVL(TRIM(REGION_ID), '(unassigned)')),
    TRUNC(CHARGE_PERIOD_START, 'MM'),
    NVL(TRIM(BILLING_CURRENCY), '(not provided)'),
    NVL(EFFECTIVE_COST, 0),
    1
  FROM TEMP_OCI_FOCUS
  WHERE CHARGE_PERIOD_START IS NOT NULL

  UNION ALL

  SELECT
    'CREATEDBY',
    COALESCE(
      NULLIF(TRIM(TAG_SPECIAL1), ''),
      NULLIF(TRIM(TAG_SPECIAL3), ''),
      '(unassigned)'
    ),
    TRUNC(CHARGE_PERIOD_START, 'MM'),
    NVL(TRIM(BILLING_CURRENCY), '(not provided)'),
    NVL(EFFECTIVE_COST, 0),
    1
  FROM TEMP_OCI_FOCUS
  WHERE CHARGE_PERIOD_START IS NOT NULL
)
GROUP BY DIMENSION_TYPE, DIMENSION_VALUE, COST_MONTH, BILLING_CURRENCY;

CREATE OR REPLACE VIEW FOCUS_OML_TOTAL_FEATURES AS
WITH LAGGED AS (
  SELECT
    DIMENSION_VALUE,
    BILLING_CURRENCY,
    COST_MONTH,
    EFFECTIVE_COST,
    ROW_COUNT,
    LAG(EFFECTIVE_COST) OVER (
      PARTITION BY DIMENSION_VALUE, BILLING_CURRENCY ORDER BY COST_MONTH
    ) AS PREVIOUS_COST,
    AVG(EFFECTIVE_COST) OVER (
      PARTITION BY DIMENSION_VALUE, BILLING_CURRENCY ORDER BY COST_MONTH
      ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS MOVING_AVG_3
  FROM FOCUS_OML_DIM_MONTHLY
  WHERE DIMENSION_TYPE = 'TOTAL'
)
SELECT
  ROW_NUMBER() OVER (
    ORDER BY DIMENSION_VALUE, BILLING_CURRENCY, COST_MONTH
  ) AS CASE_ID,
  DIMENSION_VALUE,
  BILLING_CURRENCY,
  TO_NUMBER(TO_CHAR(COST_MONTH, 'YYYYMM')) AS MONTH_KEY,
  TO_NUMBER(TO_CHAR(COST_MONTH, 'MM')) AS MONTH_NUMBER,
  EFFECTIVE_COST,
  NVL(PREVIOUS_COST, EFFECTIVE_COST) AS PREVIOUS_COST,
  MOVING_AVG_3,
  CASE
    WHEN NVL(ABS(PREVIOUS_COST), 0) = 0 THEN 0
    ELSE (EFFECTIVE_COST - PREVIOUS_COST) / ABS(PREVIOUS_COST)
  END AS CHANGE_RATIO,
  ROW_COUNT
FROM LAGGED;

CREATE OR REPLACE VIEW FOCUS_OML_SERVICE_FEATURES AS
WITH LAGGED AS (
  SELECT
    DIMENSION_VALUE,
    BILLING_CURRENCY,
    COST_MONTH,
    EFFECTIVE_COST,
    ROW_COUNT,
    LAG(EFFECTIVE_COST) OVER (
      PARTITION BY DIMENSION_VALUE, BILLING_CURRENCY ORDER BY COST_MONTH
    ) AS PREVIOUS_COST,
    AVG(EFFECTIVE_COST) OVER (
      PARTITION BY DIMENSION_VALUE, BILLING_CURRENCY ORDER BY COST_MONTH
      ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS MOVING_AVG_3
  FROM FOCUS_OML_DIM_MONTHLY
  WHERE DIMENSION_TYPE = 'SERVICE'
)
SELECT
  ROW_NUMBER() OVER (
    ORDER BY DIMENSION_VALUE, BILLING_CURRENCY, COST_MONTH
  ) AS CASE_ID,
  DIMENSION_VALUE,
  BILLING_CURRENCY,
  TO_NUMBER(TO_CHAR(COST_MONTH, 'YYYYMM')) AS MONTH_KEY,
  TO_NUMBER(TO_CHAR(COST_MONTH, 'MM')) AS MONTH_NUMBER,
  EFFECTIVE_COST,
  NVL(PREVIOUS_COST, EFFECTIVE_COST) AS PREVIOUS_COST,
  MOVING_AVG_3,
  CASE
    WHEN NVL(ABS(PREVIOUS_COST), 0) = 0 THEN 0
    ELSE (EFFECTIVE_COST - PREVIOUS_COST) / ABS(PREVIOUS_COST)
  END AS CHANGE_RATIO,
  ROW_COUNT
FROM LAGGED;

CREATE OR REPLACE VIEW FOCUS_OML_REGION_FEATURES AS
WITH LAGGED AS (
  SELECT
    DIMENSION_VALUE,
    BILLING_CURRENCY,
    COST_MONTH,
    EFFECTIVE_COST,
    ROW_COUNT,
    LAG(EFFECTIVE_COST) OVER (
      PARTITION BY DIMENSION_VALUE, BILLING_CURRENCY ORDER BY COST_MONTH
    ) AS PREVIOUS_COST,
    AVG(EFFECTIVE_COST) OVER (
      PARTITION BY DIMENSION_VALUE, BILLING_CURRENCY ORDER BY COST_MONTH
      ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS MOVING_AVG_3
  FROM FOCUS_OML_DIM_MONTHLY
  WHERE DIMENSION_TYPE = 'REGION'
)
SELECT
  ROW_NUMBER() OVER (
    ORDER BY DIMENSION_VALUE, BILLING_CURRENCY, COST_MONTH
  ) AS CASE_ID,
  DIMENSION_VALUE,
  BILLING_CURRENCY,
  TO_NUMBER(TO_CHAR(COST_MONTH, 'YYYYMM')) AS MONTH_KEY,
  TO_NUMBER(TO_CHAR(COST_MONTH, 'MM')) AS MONTH_NUMBER,
  EFFECTIVE_COST,
  NVL(PREVIOUS_COST, EFFECTIVE_COST) AS PREVIOUS_COST,
  MOVING_AVG_3,
  CASE
    WHEN NVL(ABS(PREVIOUS_COST), 0) = 0 THEN 0
    ELSE (EFFECTIVE_COST - PREVIOUS_COST) / ABS(PREVIOUS_COST)
  END AS CHANGE_RATIO,
  ROW_COUNT
FROM LAGGED;

CREATE OR REPLACE VIEW FOCUS_OML_CREATEDBY_FEATURES AS
WITH LAGGED AS (
  SELECT
    DIMENSION_VALUE,
    BILLING_CURRENCY,
    COST_MONTH,
    EFFECTIVE_COST,
    ROW_COUNT,
    LAG(EFFECTIVE_COST) OVER (
      PARTITION BY DIMENSION_VALUE, BILLING_CURRENCY ORDER BY COST_MONTH
    ) AS PREVIOUS_COST,
    AVG(EFFECTIVE_COST) OVER (
      PARTITION BY DIMENSION_VALUE, BILLING_CURRENCY ORDER BY COST_MONTH
      ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS MOVING_AVG_3
  FROM FOCUS_OML_DIM_MONTHLY
  WHERE DIMENSION_TYPE = 'CREATEDBY'
)
SELECT
  ROW_NUMBER() OVER (
    ORDER BY DIMENSION_VALUE, BILLING_CURRENCY, COST_MONTH
  ) AS CASE_ID,
  DIMENSION_VALUE,
  BILLING_CURRENCY,
  TO_NUMBER(TO_CHAR(COST_MONTH, 'YYYYMM')) AS MONTH_KEY,
  TO_NUMBER(TO_CHAR(COST_MONTH, 'MM')) AS MONTH_NUMBER,
  EFFECTIVE_COST,
  NVL(PREVIOUS_COST, EFFECTIVE_COST) AS PREVIOUS_COST,
  MOVING_AVG_3,
  CASE
    WHEN NVL(ABS(PREVIOUS_COST), 0) = 0 THEN 0
    ELSE (EFFECTIVE_COST - PREVIOUS_COST) / ABS(PREVIOUS_COST)
  END AS CHANGE_RATIO,
  ROW_COUNT
FROM LAGGED;

PROMPT Creating the FOCUS_OML_ANALYTICS package...
CREATE OR REPLACE PACKAGE FOCUS_OML_ANALYTICS AUTHID DEFINER AS
  PROCEDURE RUN(P_OUTLIER_RATE IN NUMBER DEFAULT 0.05);
END FOCUS_OML_ANALYTICS;
/

CREATE OR REPLACE PACKAGE BODY FOCUS_OML_ANALYTICS AS
  PROCEDURE DROP_MODEL_IF_EXISTS(P_MODEL_NAME IN VARCHAR2) IS
    L_COUNT NUMBER;
  BEGIN
    SELECT COUNT(*) INTO L_COUNT
    FROM USER_MINING_MODELS
    WHERE MODEL_NAME = UPPER(P_MODEL_NAME);

    IF L_COUNT > 0 THEN
      DBMS_DATA_MINING.DROP_MODEL(P_MODEL_NAME);
    END IF;
  END DROP_MODEL_IF_EXISTS;

  PROCEDURE DROP_TABLE_IF_EXISTS(P_TABLE_NAME IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ' || DBMS_ASSERT.SIMPLE_SQL_NAME(P_TABLE_NAME) || ' PURGE';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
        RAISE;
      END IF;
  END DROP_TABLE_IF_EXISTS;

  PROCEDURE APPEND_MESSAGE(
    P_MESSAGE IN VARCHAR2,
    P_BUFFER IN OUT NOCOPY VARCHAR2
  ) IS
  BEGIN
    IF P_BUFFER IS NULL THEN
      P_BUFFER := P_MESSAGE;
    ELSE
      P_BUFFER := SUBSTR(P_BUFFER || ' ' || P_MESSAGE, 1, 4000);
    END IF;
  END APPEND_MESSAGE;

  PROCEDURE BUILD_ANOMALY_MODEL(
    P_MODEL_NAME IN VARCHAR2,
    P_VIEW_NAME IN VARCHAR2,
    P_APPLY_TABLE IN VARCHAR2,
    P_DIMENSION_TYPE IN VARCHAR2,
    P_OUTLIER_RATE IN NUMBER,
    P_MESSAGE IN OUT NOCOPY VARCHAR2
  ) IS
    L_COUNT NUMBER;
    L_SETTINGS DBMS_DATA_MINING.SETTING_LIST;
    L_SQL VARCHAR2(32767);
  BEGIN
    EXECUTE IMMEDIATE
      'SELECT COUNT(*) FROM ' || DBMS_ASSERT.SIMPLE_SQL_NAME(P_VIEW_NAME)
      INTO L_COUNT;

    DROP_MODEL_IF_EXISTS(P_MODEL_NAME);
    DROP_TABLE_IF_EXISTS(P_APPLY_TABLE);

    IF L_COUNT < 12 THEN
      APPEND_MESSAGE(
        P_DIMENSION_TYPE || ' skipped: ' || L_COUNT || ' monthly records; 12 required.',
        P_MESSAGE
      );
      RETURN;
    END IF;

    L_SETTINGS('ALGO_NAME') := 'ALGO_SUPPORT_VECTOR_MACHINES';
    L_SETTINGS('PREP_AUTO') := 'ON';
    L_SETTINGS('SVMS_KERNEL_FUNCTION') := 'SVMS_GAUSSIAN';
    L_SETTINGS('SVMS_OUTLIER_RATE') := TO_CHAR(
      P_OUTLIER_RATE,
      'FM0D999999',
      'NLS_NUMERIC_CHARACTERS=''.,'''
    );

    DBMS_DATA_MINING.CREATE_MODEL2(
      MODEL_NAME => P_MODEL_NAME,
      MINING_FUNCTION => 'CLASSIFICATION',
      DATA_QUERY => 'SELECT * FROM ' || DBMS_ASSERT.SIMPLE_SQL_NAME(P_VIEW_NAME),
      SET_LIST => L_SETTINGS,
      CASE_ID_COLUMN_NAME => 'CASE_ID',
      TARGET_COLUMN_NAME => NULL
    );

    DBMS_DATA_MINING.APPLY(
      MODEL_NAME => P_MODEL_NAME,
      DATA_TABLE_NAME => P_VIEW_NAME,
      CASE_ID_COLUMN_NAME => 'CASE_ID',
      RESULT_TABLE_NAME => P_APPLY_TABLE
    );

    L_SQL :=
      'INSERT INTO FOCUS_OML_ANOMALIES (' ||
      'DIMENSION_TYPE, DIMENSION_VALUE, COST_MONTH, BILLING_CURRENCY, ' ||
      'EFFECTIVE_COST, ANOMALY_PROBABILITY, PREDICTION, MODEL_NAME) ' ||
      'SELECT :dimension_type, V.DIMENSION_VALUE, ' ||
      'TO_DATE(TO_CHAR(V.MONTH_KEY) || ''01'', ''YYYYMMDD''), ' ||
      'V.BILLING_CURRENCY, V.EFFECTIVE_COST, S.PROBABILITY, S.PREDICTION, :model_name ' ||
      'FROM ' || DBMS_ASSERT.SIMPLE_SQL_NAME(P_VIEW_NAME) || ' V ' ||
      'JOIN (' ||
      '  SELECT CASE_ID, PREDICTION, PROBABILITY FROM (' ||
      '    SELECT A.*, ROW_NUMBER() OVER (' ||
      '      PARTITION BY CASE_ID ORDER BY PROBABILITY DESC, PREDICTION' ||
      '    ) AS RN FROM ' || DBMS_ASSERT.SIMPLE_SQL_NAME(P_APPLY_TABLE) || ' A' ||
      '  ) WHERE RN = 1 AND PREDICTION = 0' ||
      ') S ON S.CASE_ID = V.CASE_ID';
    EXECUTE IMMEDIATE L_SQL USING P_DIMENSION_TYPE, P_MODEL_NAME;

    DROP_TABLE_IF_EXISTS(P_APPLY_TABLE);
    APPEND_MESSAGE(P_DIMENSION_TYPE || ' model built from ' || L_COUNT || ' records.', P_MESSAGE);
  END BUILD_ANOMALY_MODEL;

  PROCEDURE BUILD_USER_FORECAST(P_MESSAGE IN OUT NOCOPY VARCHAR2) IS
    L_CREATED_BY VARCHAR2(4000);
    L_CURRENCY VARCHAR2(100);
    L_COUNT NUMBER;
    L_MAX_INDEX NUMBER;
    L_SETTINGS DBMS_DATA_MINING.SETTING_LIST;
    L_SQL VARCHAR2(32767);
  BEGIN
    INSERT INTO FOCUS_OML_TOP_USER (CREATED_BY, BILLING_CURRENCY, YTD_COST)
    WITH BOUNDS AS (
      SELECT TRUNC(COALESCE(MAX(LOAD_DATE), MAX(CHARGE_PERIOD_START))) AS AS_OF_DATE
      FROM TEMP_OCI_FOCUS
    ), RANKED AS (
      SELECT
        COALESCE(
          NULLIF(TRIM(F.TAG_SPECIAL1), ''),
          NULLIF(TRIM(F.TAG_SPECIAL3), ''),
          '(unassigned)'
        ) AS CREATED_BY,
        NVL(TRIM(F.BILLING_CURRENCY), '(not provided)') AS BILLING_CURRENCY,
        SUM(NVL(F.EFFECTIVE_COST, 0)) AS YTD_COST,
        ROW_NUMBER() OVER (
          ORDER BY SUM(NVL(F.EFFECTIVE_COST, 0)) DESC,
                   COALESCE(
                     NULLIF(TRIM(F.TAG_SPECIAL1), ''),
                     NULLIF(TRIM(F.TAG_SPECIAL3), ''),
                     '(unassigned)'
                   ),
                   NVL(TRIM(F.BILLING_CURRENCY), '(not provided)')
        ) AS RN
      FROM TEMP_OCI_FOCUS F CROSS JOIN BOUNDS B
      WHERE B.AS_OF_DATE IS NOT NULL
        AND F.CHARGE_PERIOD_START >= TRUNC(B.AS_OF_DATE, 'YYYY')
        AND F.CHARGE_PERIOD_START < B.AS_OF_DATE + 1
        AND COALESCE(
          NULLIF(TRIM(F.TAG_SPECIAL1), ''),
          NULLIF(TRIM(F.TAG_SPECIAL3), ''),
          '(unassigned)'
        ) <> '(unassigned)'
      GROUP BY
        COALESCE(
          NULLIF(TRIM(F.TAG_SPECIAL1), ''),
          NULLIF(TRIM(F.TAG_SPECIAL3), ''),
          '(unassigned)'
        ),
        NVL(TRIM(F.BILLING_CURRENCY), '(not provided)')
    )
    SELECT CREATED_BY, BILLING_CURRENCY, YTD_COST
    FROM RANKED
    WHERE RN = 1;

    BEGIN
      SELECT CREATED_BY, BILLING_CURRENCY
      INTO L_CREATED_BY, L_CURRENCY
      FROM FOCUS_OML_TOP_USER
      FETCH FIRST 1 ROW ONLY;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        APPEND_MESSAGE('Forecast skipped: no year-to-date CreatedBy cost data.', P_MESSAGE);
        RETURN;
    END;

    INSERT INTO FOCUS_OML_TOP_USER_TS (TIME_INDEX, COST_MONTH, EFFECTIVE_COST)
    WITH DATA_BOUNDS AS (
      SELECT TRUNC(COALESCE(MAX(LOAD_DATE), MAX(CHARGE_PERIOD_START))) AS AS_OF_DATE
      FROM TEMP_OCI_FOCUS
    ), AGGREGATED AS (
      SELECT
        TRUNC(F.CHARGE_PERIOD_START, 'MM') AS COST_MONTH,
        SUM(NVL(F.EFFECTIVE_COST, 0)) AS EFFECTIVE_COST
      FROM TEMP_OCI_FOCUS F CROSS JOIN DATA_BOUNDS B
      WHERE F.CHARGE_PERIOD_START IS NOT NULL
        AND F.CHARGE_PERIOD_START < B.AS_OF_DATE + 1
        AND COALESCE(
          NULLIF(TRIM(F.TAG_SPECIAL1), ''),
          NULLIF(TRIM(F.TAG_SPECIAL3), ''),
          '(unassigned)'
        ) = L_CREATED_BY
        AND NVL(TRIM(F.BILLING_CURRENCY), '(not provided)') = L_CURRENCY
      GROUP BY TRUNC(F.CHARGE_PERIOD_START, 'MM')
    ), BOUNDS AS (
      SELECT MIN(COST_MONTH) AS MIN_MONTH, MAX(COST_MONTH) AS MAX_MONTH
      FROM AGGREGATED
    ), MONTHS AS (
      SELECT ADD_MONTHS(MIN_MONTH, LEVEL - 1) AS COST_MONTH
      FROM BOUNDS
      CONNECT BY LEVEL <= MONTHS_BETWEEN(MAX_MONTH, MIN_MONTH) + 1
    )
    SELECT
      ROW_NUMBER() OVER (ORDER BY M.COST_MONTH),
      M.COST_MONTH,
      NVL(A.EFFECTIVE_COST, 0)
    FROM MONTHS M
    LEFT JOIN AGGREGATED A ON A.COST_MONTH = M.COST_MONTH;

    SELECT COUNT(*), NVL(MAX(TIME_INDEX), 0)
    INTO L_COUNT, L_MAX_INDEX
    FROM FOCUS_OML_TOP_USER_TS;

    DROP_MODEL_IF_EXISTS('FOCUS_OML_USER_ESM');
    IF L_COUNT < 6 THEN
      APPEND_MESSAGE(
        'Forecast skipped: ' || L_COUNT || ' monthly observations; 6 required.',
        P_MESSAGE
      );
      RETURN;
    END IF;

    L_SETTINGS('ALGO_NAME') := 'ALGO_EXPONENTIAL_SMOOTHING';
    L_SETTINGS('EXSM_PREDICTION_STEP') := '6';
    DBMS_DATA_MINING.CREATE_MODEL2(
      MODEL_NAME => 'FOCUS_OML_USER_ESM',
      MINING_FUNCTION => 'TIME_SERIES',
      DATA_QUERY => 'SELECT TIME_INDEX, EFFECTIVE_COST FROM FOCUS_OML_TOP_USER_TS',
      SET_LIST => L_SETTINGS,
      CASE_ID_COLUMN_NAME => 'TIME_INDEX',
      TARGET_COLUMN_NAME => 'EFFECTIVE_COST'
    );

    L_SQL := q'[
      INSERT INTO FOCUS_OML_FORECAST (
        CREATED_BY, BILLING_CURRENCY, FORECAST_MONTH, HORIZON_MONTHS,
        PREDICTION, LOWER_BOUND, UPPER_BOUND
      )
      SELECT
        :created_by,
        :currency,
        ADD_MONTHS(B.MAX_MONTH, V.CASE_ID - :max_index),
        V.CASE_ID - :max_index,
        V.PREDICTION,
        NVL(V.LOWER, V.PREDICTION),
        NVL(V.UPPER, V.PREDICTION)
      FROM DM$VPFOCUS_OML_USER_ESM V
      CROSS JOIN (SELECT MAX(COST_MONTH) AS MAX_MONTH FROM FOCUS_OML_TOP_USER_TS) B
      WHERE V.CASE_ID > :max_index
        AND V.CASE_ID <= :max_index + 6
      ORDER BY V.CASE_ID]';
    EXECUTE IMMEDIATE L_SQL
      USING L_CREATED_BY, L_CURRENCY, L_MAX_INDEX, L_MAX_INDEX, L_MAX_INDEX, L_MAX_INDEX;
    APPEND_MESSAGE(
      'Forecast model built for CreatedBy=' || L_CREATED_BY || ', currency=' || L_CURRENCY || '.',
      P_MESSAGE
    );
  END BUILD_USER_FORECAST;

  PROCEDURE RUN(P_OUTLIER_RATE IN NUMBER DEFAULT 0.05) IS
    L_MESSAGE VARCHAR2(4000);
  BEGIN
    IF P_OUTLIER_RATE < 0.001 OR P_OUTLIER_RATE > 0.25 THEN
      RAISE_APPLICATION_ERROR(-20003, 'Outlier rate must be between 0.001 and 0.25');
    END IF;

    DELETE FROM FOCUS_OML_ANOMALIES;
    DELETE FROM FOCUS_OML_FORECAST;
    DELETE FROM FOCUS_OML_TOP_USER_TS;
    DELETE FROM FOCUS_OML_TOP_USER;

    BUILD_ANOMALY_MODEL(
      'FOCUS_OML_TOTAL', 'FOCUS_OML_TOTAL_FEATURES', 'FOCUS_OML_APPLY_TOTAL',
      'TOTAL', P_OUTLIER_RATE, L_MESSAGE
    );
    BUILD_ANOMALY_MODEL(
      'FOCUS_OML_SERVICE', 'FOCUS_OML_SERVICE_FEATURES', 'FOCUS_OML_APPLY_SERVICE',
      'SERVICE', P_OUTLIER_RATE, L_MESSAGE
    );
    BUILD_ANOMALY_MODEL(
      'FOCUS_OML_REGION', 'FOCUS_OML_REGION_FEATURES', 'FOCUS_OML_APPLY_REGION',
      'REGION', P_OUTLIER_RATE, L_MESSAGE
    );
    BUILD_ANOMALY_MODEL(
      'FOCUS_OML_CREATEDBY', 'FOCUS_OML_CREATEDBY_FEATURES', 'FOCUS_OML_APPLY_CREATEDBY',
      'CREATEDBY', P_OUTLIER_RATE, L_MESSAGE
    );
    BUILD_USER_FORECAST(L_MESSAGE);

    INSERT INTO FOCUS_OML_RUNS (STATUS, MESSAGE, OUTLIER_RATE)
    VALUES ('SUCCEEDED', NVL(L_MESSAGE, 'OML refresh completed.'), P_OUTLIER_RATE);
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      BEGIN
        INSERT INTO FOCUS_OML_RUNS (STATUS, MESSAGE, OUTLIER_RATE)
        VALUES ('FAILED', SUBSTR(SQLERRM, 1, 4000), P_OUTLIER_RATE);
        COMMIT;
      EXCEPTION
        WHEN OTHERS THEN NULL;
      END;
      RAISE;
  END RUN;
END FOCUS_OML_ANALYTICS;
/

SHOW ERRORS PACKAGE FOCUS_OML_ANALYTICS
SHOW ERRORS PACKAGE BODY FOCUS_OML_ANALYTICS

PROMPT Installation complete. Refresh explicitly with:
PROMPT   BEGIN FOCUS_OML_ANALYTICS.RUN(0.05); END;
PROMPT   /

COMMIT;
