-- Remove only the optional FOCUS_OML_* package, models, views, and result tables.
-- TEMP_OCI_FOCUS is never modified or removed.

WHENEVER SQLERROR CONTINUE
SET SERVEROUTPUT ON

BEGIN
  FOR model_row IN (
    SELECT MODEL_NAME
    FROM USER_MINING_MODELS
    WHERE MODEL_NAME LIKE 'FOCUS_OML_%'
  ) LOOP
    DBMS_DATA_MINING.DROP_MODEL(model_row.MODEL_NAME);
  END LOOP;
END;
/

DROP PACKAGE FOCUS_OML_ANALYTICS;
DROP VIEW FOCUS_OML_CREATEDBY_FEATURES;
DROP VIEW FOCUS_OML_REGION_FEATURES;
DROP VIEW FOCUS_OML_SERVICE_FEATURES;
DROP VIEW FOCUS_OML_TOTAL_FEATURES;
DROP VIEW FOCUS_OML_DIM_MONTHLY;
DROP TABLE FOCUS_OML_APPLY_CREATEDBY PURGE;
DROP TABLE FOCUS_OML_APPLY_REGION PURGE;
DROP TABLE FOCUS_OML_APPLY_SERVICE PURGE;
DROP TABLE FOCUS_OML_APPLY_TOTAL PURGE;
DROP TABLE FOCUS_OML_TOP_USER_TS PURGE;
DROP TABLE FOCUS_OML_TOP_USER PURGE;
DROP TABLE FOCUS_OML_FORECAST PURGE;
DROP TABLE FOCUS_OML_ANOMALIES PURGE;
DROP TABLE FOCUS_OML_RUNS PURGE;

COMMIT;
PROMPT Optional FOCUS OML objects removed; TEMP_OCI_FOCUS was preserved.
