#!/usr/bin/env bash

set -euo pipefail

ADMIN_USER=${1:-${ADMIN_USER:-}}
ADMIN_PASS=${2:-${ADMIN_PASS:-}}
DB_CONN=${3:-${DB_CONN:-}}
TARGET_SCHEMA=${4:-${TARGET_SCHEMA:-}}
TARGET_PASS=${5:-${TARGET_PASS:-}}
CONFIG_FILE=${6:-${CONFIG_FILE:-focus.conf}}
DROP_EXISTING=${DROP_EXISTING:-true}

if [ -z "${ADMIN_PASS:-}" ] && [ -t 0 ]; then
  read -r -s -p "Oracle admin password: " ADMIN_PASS
  echo
fi
if [ -z "${TARGET_PASS:-}" ] && [ -t 0 ]; then
  read -r -s -p "Target schema password: " TARGET_PASS
  echo
fi

if [ -z "${ADMIN_USER:-}" ] || [ -z "${ADMIN_PASS:-}" ] || [ -z "${DB_CONN:-}" ] || [ -z "${TARGET_SCHEMA:-}" ] || [ -z "${TARGET_PASS:-}" ]; then
  echo "Usage:"
  echo "$0 <admin_user> <admin_pass> <tns> <schema> <schema_pass> [config_file]"
  echo "Or set ADMIN_USER, DB_CONN, TARGET_SCHEMA, and optionally CONFIG_FILE; passwords are prompted on a terminal."
  exit 1
fi

if ! command -v sqlplus >/dev/null 2>&1; then
  echo "sqlplus not found in PATH"
  exit 1
fi

if [ ! -f "$CONFIG_FILE" ]; then
  echo "Config file not found: $CONFIG_FILE"
  exit 1
fi

if [[ ! "$TARGET_SCHEMA" =~ ^[A-Za-z][A-Za-z0-9_\$#]*$ ]]; then
  echo "Invalid schema name: $TARGET_SCHEMA"
  echo "Use an unquoted Oracle identifier: starts with a letter, then letters/numbers/_/$/#"
  exit 1
fi

case "$(printf '%s' "$DROP_EXISTING" | tr '[:upper:]' '[:lower:]')" in
  true|yes|1|false|no|0) ;;
  *)
    echo "Invalid DROP_EXISTING value: $DROP_EXISTING"
    echo "Use true/false, yes/no, or 1/0"
    exit 1
    ;;
esac

SCHEMA=$(printf '%s' "$TARGET_SCHEMA" | tr '[:lower:]' '[:upper:]')
TARGET_PASS_SQL=${TARGET_PASS//\"/\"\"}

T_FOCUS=TEMP_OCI_FOCUS
T_TAGS=TEMP_OCI_FOCUS_TAGS
T_TAG_KEYS=TEMP_OCI_FOCUS_TAG_KEYS
T_STATS=TEMP_OCI_FOCUS_STATS
T_LOAD=TEMP_OCI_FOCUS_LOAD_STATUS
T_REF=TEMP_OCI_FOCUS_REFERENCE
T_SQLLOADER_AUDIT=SQLLOADER_AUDIT

FQN_FOCUS=${SCHEMA}.${T_FOCUS}
FQN_TAGS=${SCHEMA}.${T_TAGS}
FQN_TAG_KEYS=${SCHEMA}.${T_TAG_KEYS}
FQN_STATS=${SCHEMA}.${T_STATS}
FQN_LOAD=${SCHEMA}.${T_LOAD}
FQN_REF=${SCHEMA}.${T_REF}
FQN_SQLLOADER_AUDIT=${SCHEMA}.${T_SQLLOADER_AUDIT}

sqlplus "${ADMIN_USER}/${ADMIN_PASS}@${DB_CONN}" <<EOF

WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO OFF

PROMPT ============================================
PROMPT STARTING SCHEMA DEPLOYMENT
PROMPT ============================================

PROMPT ---- Preparing target schema owner ----

DECLARE
  v_count NUMBER;
  v_drop_existing VARCHAR2(10) := LOWER('${DROP_EXISTING}');
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM all_users
  WHERE username = UPPER('${SCHEMA}');

  IF v_count > 0 THEN
    IF v_drop_existing IN ('true', 'yes', '1') THEN
      EXECUTE IMMEDIATE 'DROP USER ${SCHEMA} CASCADE';
      DBMS_OUTPUT.PUT_LINE('Existing user dropped');
      v_count := 0;
    ELSE
      EXECUTE IMMEDIATE 'ALTER USER ${SCHEMA} IDENTIFIED BY "${TARGET_PASS_SQL}"';
      DBMS_OUTPUT.PUT_LINE('Existing user retained and password updated');
    END IF;
  END IF;

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER ${SCHEMA} IDENTIFIED BY "${TARGET_PASS_SQL}"';
    DBMS_OUTPUT.PUT_LINE('User created');
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM all_users
  WHERE username = UPPER('${SCHEMA}');

  IF v_count = 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'Target schema was not created: ${SCHEMA}');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Verified target schema owner: ${SCHEMA}');
  END IF;
END;
/
PROMPT ---- Granting privileges ----

GRANT CONNECT, DWROLE TO ${SCHEMA};
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE TO ${SCHEMA};
GRANT UNLIMITED TABLESPACE TO ${SCHEMA};



PROMPT ---- Switching to schema ${SCHEMA} ----
ALTER SESSION SET CURRENT_SCHEMA=${SCHEMA};



PROMPT ---- Creating main table ----


-- =====================================
-- Create main table
-- =====================================
CREATE TABLE ${FQN_FOCUS}
(
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
	"SOURCE_TENANT_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SOURCE_FILE_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"BILLING_ACCOUNT_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"BILLING_ACCOUNT_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"BILLING_ACCOUNT_TYPE" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SUB_ACCOUNT_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SUB_ACCOUNT_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SUB_ACCOUNT_TYPE" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"INVOICE_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"INVOICE_ISSUER" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"PROVIDER" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"PUBLISHER" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"PRICING_CATEGORY" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"PRICING_CURRENCY_CONTRACTED_UP" NUMBER,
	"PRICING_CURRENCY_EFFECTIVE_COST" NUMBER,
	"PRICING_CURRENCY_LIST_UNIT_PRICE" NUMBER,
	"PRICING_QUANTITY" NUMBER,
	"PRICING_UNIT" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"BILLING_PERIOD_START" DATE,
	"BILLING_PERIOD_END" DATE,
	"CHARGE_PERIOD_START" DATE,
	"CHARGE_PERIOD_END" DATE,
	"BILLED_COST" NUMBER,
	"BILLING_CURRENCY" VARCHAR2(100) COLLATE "USING_NLS_COMP",
	"CONSUMED_QUANTITY" NUMBER,
	"CONSUMED_UNIT" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"CONTRACTED_COST" NUMBER,
	"CONTRACTED_UNIT_PRICE" NUMBER,
	"EFFECTIVE_COST" NUMBER,
	"LIST_COST" NUMBER,
	"LIST_UNIT_PRICE" NUMBER,
	"AVAILABILITY_ZONE" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"REGION_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"REGION_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"RESOURCE_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"RESOURCE_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"RESOURCE_TYPE" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"TAGS" VARCHAR2(32627) COLLATE "USING_NLS_COMP",
	"SERVICE_CATEGORY" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SERVICE_SUB_CATEGORY" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SERVICE_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"CAPACITY_RESERVATION_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"CAPACITY_RESERVATION_STATUS" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"CHARGE_CATEGORY" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"CHARGE_CLASS" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"CHARGE_DESCRIPTION" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"CHARGE_FREQUENCY" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"COMMITMENT_DISCOUNT_CATEGORY" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"COMMITMENT_DISCOUNT_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"COMMITMENT_DISCOUNT_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"COMMITMENT_DISCOUNT_QUANTITY" NUMBER,
	"COMMITMENT_DISCOUNT_STATUS" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"COMMITMENT_DISCOUNT_TYPE" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"COMMITMENT_DISCOUNT_UNIT" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SKU_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SKU_PRICE_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SKU_PRICE_DETAILS" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"SKU_METER" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"USAGE_QUANTITY" NUMBER,
	"USAGE_UNIT" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"OCI_REFERENCE_NUMBER" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"OCI_COMPARTMENT_ID" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"OCI_COMPARTMENT_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"OCI_COMPARTMENT_PATH" VARCHAR2(4000) COLLATE "USING_NLS_COMP",
	"OCI_OVERAGE_FLAG" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"OCI_UNIT_PRICE_OVERAGE" NUMBER,
	"OCI_BILLED_QUANTITY_OVERAGE" NUMBER,
	"OCI_COST_OVERAGE" NUMBER,
	"OCI_ATTRIBUTED_USAGE" NUMBER,
	"OCI_ATTRIBUTED_COST" NUMBER,
	"OCI_BACK_REFERENCE_NUMBER" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"TAG_SPECIAL1" VARCHAR2(4000) COLLATE "USING_NLS_COMP",
	"TAG_SPECIAL2" VARCHAR2(4000) COLLATE "USING_NLS_COMP",
	"TAG_SPECIAL3" VARCHAR2(4000) COLLATE "USING_NLS_COMP",
	"TAG_SPECIAL4" VARCHAR2(4000) COLLATE "USING_NLS_COMP",
    "LOAD_DATE"            DATE DEFAULT SYSDATE
--    CONSTRAINT TEMP_OCI_FOCUS_PK PRIMARY KEY (ID)
)
COMPRESS FOR QUERY HIGH
PARTITION BY RANGE (CHARGE_PERIOD_START)
INTERVAL (NUMTOYMINTERVAL(1,'MONTH'))
(
    PARTITION p_init VALUES LESS THAN (DATE '2025-01-01')
);




-- CREATE INDEX ${SCHEMA}.TEMP_OCI_FOCUS_TENANT_DT
-- ON ${FQN_FOCUS} (SOURCE_TENANT_NAME, CHARGE_PERIOD_START)
-- LOCAL;

-- CREATE INDEX ${SCHEMA}.TEMP_OCI_FOCUS_RESOURCE
-- ON ${FQN_FOCUS} (RESOURCE_ID)
-- LOCAL;




-- =====================================
-- Create TEMP_OCI_FOCUS_LOAD_STATUS
-- =====================================
CREATE TABLE ${FQN_LOAD}
(
  SOURCE_TENANT_NAME VARCHAR2(1000) NOT NULL,
  FILE_TYPE          VARCHAR2(1000) NOT NULL,
  FILE_ID            VARCHAR2(1000) NOT NULL,
  FILE_NAME          VARCHAR2(1000) NOT NULL,
  FILE_DATE          DATE,
  FILE_SIZE          NUMBER,
  NUM_ROWS           NUMBER,
  LOAD_START_TIME    DATE,
  LOAD_END_TIME      DATE,
  AGENT_VERSION      VARCHAR2(100),
  BATCH_ID           NUMBER,
  BATCH_TOTAL        NUMBER,
  CONSTRAINT TEMP_OCI_FOCUS_LOAD_STATUS_PK
  PRIMARY KEY (SOURCE_TENANT_NAME, FILE_NAME)
);


-- =====================================
-- Create SQLLOADER_AUDIT
-- =====================================
CREATE TABLE ${FQN_SQLLOADER_AUDIT}
(
    ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SOURCE_TENANT_NAME  VARCHAR2(255),
    FILE_ID             VARCHAR2(512),
    FILE_NAME           VARCHAR2(1024),
    DATA_FILE           VARCHAR2(1024),
    LOG_FILE            VARCHAR2(1024),
    STATUS              VARCHAR2(30),
    ROWS_INSERTED       NUMBER,
    ROWS_FAILED         NUMBER,
    ROWS_REJECTED       NUMBER,
    ROWS_DISCARDED      NUMBER,
    ROWS_SKIPPED        NUMBER,
    TOTAL_ROWS_READ     NUMBER,
    TOTAL_FILE_LINES    NUMBER,
    FILE_SIZE_BYTES     NUMBER,
    LOADER_START_TIME   TIMESTAMP,
    LOADER_END_TIME     TIMESTAMP,
    DURATION_SECONDS    NUMBER,
    ERROR_MESSAGE       VARCHAR2(4000),
    INSERTED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX ${SCHEMA}.SQLLOADER_AUDIT_N1
    ON ${FQN_SQLLOADER_AUDIT} (SOURCE_TENANT_NAME, FILE_NAME);

CREATE INDEX ${SCHEMA}.SQLLOADER_AUDIT_N2
    ON ${FQN_SQLLOADER_AUDIT} (INSERTED_AT);


-- Create TEMP_OCI_FOCUS_STATS
-- =====================================
CREATE TABLE ${FQN_STATS}
(
  SOURCE_TENANT_NAME   VARCHAR2(1000),
  SOURCE_FILE_ID       VARCHAR2(1000),
  CHARGE_PERIOD_START  DATE,
  NUM_ROWS             NUMBER,
  EFFECTIVE_COST       NUMBER,
  BILLING_CURRENCY     VARCHAR2(1000),
  UPDATE_DATE          DATE,
  AGENT_VERSION        VARCHAR2(30),
  CONSTRAINT TEMP_OCI_FOCUS_STATS_PK
  PRIMARY KEY (SOURCE_TENANT_NAME, SOURCE_FILE_ID, CHARGE_PERIOD_START)
);



CREATE TABLE ${FQN_TAG_KEYS}
(
    "SOURCE_TENANT_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
    "TAG_KEY"            VARCHAR2(1000) COLLATE "USING_NLS_COMP",
    "TAG_VALUE"          VARCHAR2(4000) COLLATE "USING_NLS_COMP",
    CONSTRAINT TEMP_OCI_FOCUS_TAG_KEYS_PK
        PRIMARY KEY ("SOURCE_TENANT_NAME", "TAG_KEY", "TAG_VALUE")
        USING INDEX ENABLE
);


CREATE TABLE ${FQN_REF}
(
    "SOURCE_TENANT_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
    "REF_TYPE"           VARCHAR2(1000) COLLATE "USING_NLS_COMP",
    "REF_NAME"           VARCHAR2(1000) COLLATE "USING_NLS_COMP",
    CONSTRAINT TEMP_OCI_FOCUS_REFERENCE_PK
    PRIMARY KEY ("SOURCE_TENANT_NAME", "REF_TYPE", "REF_NAME")
    USING INDEX ENABLE
)
DEFAULT COLLATION "USING_NLS_COMP";



-- drop  table ${FQN_TAGS} cascade constraints;
-- =====================================
-- Create TAGS table
-- =====================================
CREATE TABLE ${FQN_TAGS} (
    SOURCE_TENANT_NAME   VARCHAR2(200)   NOT NULL,
    RESOURCE_ID          VARCHAR2(500),
    CHARGE_PERIOD_START  VARCHAR2(200)           NOT NULL,
    TAG_KEY              VARCHAR2(200)   NOT NULL,
    TAG_VALUE            VARCHAR2(4000)
)
COMPRESS FOR QUERY HIGH
NOLOGGING;

CREATE INDEX ${SCHEMA}.TEMP_OCI_FOCUS_TAGS_IX1
ON ${FQN_TAGS} (TAG_KEY, TAG_VALUE)
NOLOGGING;


PROMPT ---- Verifying created objects are owned by ${SCHEMA} ----
COLUMN OWNER FORMAT A30
COLUMN OBJECT_TYPE FORMAT A20
COLUMN OBJECT_NAME FORMAT A40

SELECT OWNER, OBJECT_TYPE, OBJECT_NAME
FROM ALL_OBJECTS
WHERE OWNER = UPPER('${SCHEMA}')
  AND OBJECT_NAME IN (
    '${T_FOCUS}',
    '${T_TAGS}',
    '${T_TAG_KEYS}',
    '${T_STATS}',
    '${T_LOAD}',
    '${T_REF}',
    '${T_SQLLOADER_AUDIT}',
    'TEMP_OCI_FOCUS_TAGS_IX1',
    'SQLLOADER_AUDIT_N1',
    'SQLLOADER_AUDIT_N2'
  )
ORDER BY OBJECT_TYPE, OBJECT_NAME;

PROMPT ============================================
PROMPT SCHEMA DEPLOYMENT COMPLETE
PROMPT ============================================

EXIT
EOF

if command -v python3 >/dev/null 2>&1; then
  python3 - "$CONFIG_FILE" "$SCHEMA" \
    "$T_FOCUS" "$T_TAGS" "$T_TAG_KEYS" "$T_STATS" "$T_LOAD" "$T_REF" "$T_SQLLOADER_AUDIT" <<'PY'
import configparser
import sys
from pathlib import Path

config_file = Path(sys.argv[1])
schema = sys.argv[2]
focus, tags, tag_keys, stats, load_status, reference, sqlloader_audit = sys.argv[3:10]

parser = configparser.ConfigParser(strict=False)
parser.optionxform = str
parser.read(config_file)

if not parser.has_section("database"):
    parser.add_section("database")
parser.set("database", "schema", schema)

if not parser.has_section("tables"):
    parser.add_section("tables")

table_values = {
    "FOCUS": focus,
    "TAGS": tags,
    "FOCUS_TAGS": tags,
    "TAG_KEYS": tag_keys,
    "TAG_KEYS_REF": tag_keys,
    "STATS": stats,
    "LOAD_STATUS": load_status,
    "REFERENCE": reference,
    "SQLLOADER_AUDIT": sqlloader_audit,
}

for key, value in table_values.items():
    parser.set("tables", key, value)

with config_file.open("w", encoding="utf-8") as handle:
    parser.write(handle)
PY
  echo "Config file updated: $CONFIG_FILE"
else
  cat >> "$CONFIG_FILE" <<EOF_CONFIG

# Added by deploy_focus_schema_with_sqlloader_audit.sh
[database]
schema = ${SCHEMA}

[tables]
FOCUS = ${T_FOCUS}
TAGS = ${T_TAGS}
FOCUS_TAGS = ${T_TAGS}
TAG_KEYS = ${T_TAG_KEYS}
TAG_KEYS_REF = ${T_TAG_KEYS}
STATS = ${T_STATS}
LOAD_STATUS = ${T_LOAD}
REFERENCE = ${T_REF}
SQLLOADER_AUDIT = ${T_SQLLOADER_AUDIT}
EOF_CONFIG
  echo "python3 not found; appended config block to: $CONFIG_FILE"
fi

echo "Done. Objects are schema-qualified under ${SCHEMA} and focus.conf points to that schema."
